# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://wenzhang-dev.github.io
date_format: "ordinal"
title: wenzhang-dev's blogs
subtitle: ""
description: "wenzhang-dev's blog"
keywords: 源代码, golang, c, cpp, c++, rust
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: wenzhang-dev
organization: Weibo, Inc.
organization_url: http://www.weibo.com
github_username: wenzhang
location: Beijing, China
email: 244680679@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: wenzhang-dev/wenzhang-dev.github.io

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: tupian
    repo: blog-comments
    oauth:
        client_id: 70809c20848b57cbfd8f
        client_secret: 6594f8cb9d98c40af81ef0049d12e29fed81b240
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: tupian
    repo: blog-comments
    clientID: 70809c20848b57cbfd8f
    clientSecret: 6594f8cb9d98c40af81ef0049d12e29fed81b240
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-110226116-1
